hotel/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView, LogoutView
# from restaurants.views import home, about, contact, ContactView
from restaurants.views import HomeView
from menus.views import HomeView
from profiles.views import ProfileFollowToggle
from profiles.views import ProfileFollowToggle, RegisterView
from profiles.views import ProfileFollowToggle, RegisterView, activate_user_view

"""from restaurants.views import (
    restaurant_listview, restaurant_detailview, restaurant_createview,
    RestaurantListView, RestaurantDetailView, RestaurantCreateView
)"""


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^activate/(?P<code>[a-z0-9].*)/$', activate_user_view, name='activate'),
    # url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    # url(r'^$', HomeView.as_view()), How django works
    # url(r'^$', TemplateView.as_view(template_name='home.html')),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^profile-follow/$', ProfileFollowToggle.as_view(), name='follow'),
    url(r'^restaurants/', include('restaurants.urls', namespace='restaurants')),
    url(r'^menus/', include('menus.urls', namespace='menus')),
    url(r'^profiles/', include('profiles.urls', namespace='profiles')),
    # url(r'^restaurants/$', restaurant_listview),
    # url(r'^restaurants/create/$', restaurant_createview),
    # url(r'^restaurants/create/$', RestaurantCreateView.as_view()),
    # url(r'^restaurants/$', RestaurantListView.as_view()),
    # url(r'^restaurants/create/$', restaurant_createview),
    # url(r'^restaurants/$', restaurant_detailview),
    # url(r'^restaurants/$', RestaurantListView.as_view()),
    # url(r'^restaurants/(?P<rest_id>\w+)$', RestaurantDetailView.as_view()),
    # url(r'^restaurants/(?P<slug>[\w-]+)/$', RestaurantDetailView.as_view()),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
    # url(r'^contact/$', contact),
    url(r'^contact/$', TemplateView.as_view(template_name='contact.html'), name='contact'),
]

menus/urls.py
# Menus urls


from django.conf.urls import url
from .views import ItemListView, ItemCreateView, ItemDetailView, ItemUpdateView


urlpatterns = [
    url(r'^create/$', ItemCreateView.as_view(), name='create'),
    # url(r'^(?P<pk>\d+)/$', ItemUpdateView.as_view(), name='update'),
    # url(r'^(?P<pk>\d+)/$', ItemDetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/$', ItemUpdateView.as_view(), name='detail'),
    url(r'$', ItemListView.as_view(), name='list'),
]

menus/models.py
from django.conf import settings
from django.db import models
from restaurants.models import RestaurantLocation
from django.core.urlresolvers import reverse
# Create your models here.


class Item(models.Model):
    """Menu Item model is created"""

    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    restaurant = models.ForeignKey(RestaurantLocation)
    name = models.CharField(max_length=120)
    contents = models.TextField(help_text='Separate each item by comma')
    excludes = models.TextField(blank=True, null=True, help_text='Separate ech item by comma')
    public = models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('menus:detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['-updated', '-timestamp']

    def get_contents(self):
        return self.contents.split(",")

    def get_excludes(self):
        return self.excludes.split(",")

menus/forms.py
# Form for menus.


from django import forms
from .models import Item
from restaurants.models import RestaurantLocation


class ItemForm(forms.ModelForm):
    """Item Entry Form"""

    class Meta:
        model = Item
        fields = [
            'restaurant',
            'name',
            'contents',
            'excludes',
            'public'
        ]

    def __init__(self, user=None, *args, **kwargs):
        print(user)
        print(kwargs)
        super(ItemForm, self).__init__(*args, **kwargs)
        self.fields['restaurant'].queryset = RestaurantLocation.objects.filter(owner=user)

menus/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views.generic import View, ListView, DetailView, CreateView, UpdateView
from .forms import ItemForm
from .models import Item
# Create your views here.


class HomeView(View):
    """Item View created"""

    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated():
            return render(request, 'home.html', {})
        user = request.user
        is_following_user_ids = [x.user.id for x in user.is_following.all()]
        qs = Item.objects.filter(user__id__in=is_following_user_ids, public=True).order_by('updated')[:3]
        return render(request, 'menus/home-feed.html', {'object_list': qs})


class ItemListView(LoginRequiredMixin, ListView):
    """Items list"""

    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)


class ItemDetailView(LoginRequiredMixin, DetailView):
    """Item Details"""

    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)


# class ItemCreateView(CreateView):
class ItemCreateView(LoginRequiredMixin, CreateView):
    """Item Creation"""

    template_name = 'forms.html'
    form_class = ItemForm

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.user = self.request.user
        return super(ItemCreateView, self).form_valid(form)

    def get_form_kwargs(self):
        kwargs = super(ItemCreateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)

    def get_context_data(self, *args, **kwargs):
        context = super(ItemCreateView, self).get_context_data(*args, **kwargs)
        context['title'] = 'Create Item'
        return context


# class ItemUpdateView(UpdateView):
class ItemUpdateView(LoginRequiredMixin, UpdateView):
    """Item update"""

    template_name = 'menus/detail-update.html'
    form_class = ItemForm

    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)

    def get_context_data(self, *args, **kwargs):
        context = super(ItemUpdateView, self).get_context_data(*args, **kwargs)
        context['title'] = 'Update Item'
        return context

    def get_form_kwargs(self):
        kwargs = super(ItemUpdateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

menus/templates/menus/detail-update.html
{% extends 'base.html' %}

{% block head_title %}{{ form.instance.name }}| Menu Items |{{ block.super }} {% endblock head_title %}

{% block content %}
<h1>{{ form.instance.name }}</h1>
<p>Location: {{ form.instance.location.name }}</p>
{% if form.instance.contents %}
    Contents
<ul>
    {% for item in form.instance.get_contents %}
    <li>{{ item }}</li>
    {% endfor %}
</ul>
{% endif %}

{% if form.instance.excludes %}
<ul>
    {% for item in form.instance.get_excludes %}
    <li>{{ item }}</li>
    {% endfor %}
</ul>
{% endif %}

<hr />
<h3>Make Changes</h3>
{% include 'snippets/form-snippet.html' with form=form %}
{% endblock content %}

menus/templates/menus/home-feed.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="col-sm-6 text-center col-sm-offset-3">
        <h1>User Following Feed</h1>
        {% for obj in object_list %}
        <div class="thumbnail">
            <h3><a href="{% url 'profiles:detail' username=obj.user.username %}">{{ obj.user.username}}</a></h3>
            <h4>{{ obj.name }}</h4>
            <p><a href="{% url 'profiles:detail' username=obj.user.username %}?q={{ obj.restaurant.title }}">

            {{ obj.restaurant.title }}</a>|
                <a href="{% url 'profiles:detail' username=obj.user.username %}?q={{ obj.restaurant.location }}">
            {{ obj.restaurant.location }}</a>|
                <a href="{% url 'profiles:detail' username=obj.user.username %}?q={{ obj.restaurant.category }}">
            {{ obj.restaurant.category }}</a></p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

menus/templates/menus/item_detail.py.html
{% extends 'base.py' %}

{% block head_title %}Menu Items | {{ block.super }}{% endblock head_title %}

{%  block content %}
<h1>{{ object.name }}</h1>
<p>Location: {{ object.restaurant.name }}</p>
{% if object.contents %}
Contents
<ul>
    {% for item in object.get_contents %}
    <li>{{ item }}</li>
    {% endfor %}
</ul>
{% endif %}

{% if object.excludes  %}
Excludes
<ul>
    {% for item in object.get_excludes %}
    <li>item</li>
    {% endfor %}
</ul>
{%  endblock content %}

menus/templates/menus/item_list.html
{% extends 'base.html' %}

{% block head_title %}Menu Items | {{ block.super }}{% endblock head_title %}

{% block content %}
<h1>Menu Items<small><a href="{% url 'menus:create' %}">Add</a></small></h1>

<ul>
    {% for obj in object_list %}
    <li><a href="{{ obj.get_absolute_url }}">{{ obj.name }}</a><br />
        {% if obj.contents %}
        Contents
        <ul>
            {% for item in obj.get_contents %}
            <li>{{ item }}</li>
            {% endfor %}
        </ul>
        {% endif %}

        {% if obj.excludes %}
        Excludes
        <ul>
            {% for item in obj.get_excludes %}
            <li>{{ item }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </li>
    {% empty %}
    <li><a href="{% url 'menus:create' %}">Add Menu Item</a></li>

    {% endfor %}
</ul>
{% endblock content %}